// <auto-generated />
using System;
using MamaCare.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MamaCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421225557_AddRiskLevelToTriageSession")]
    partial class AddRiskLevelToTriageSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MamaCare.API.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("MotherId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MotherId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 1,
                            Notes = "28-week anatomy scan",
                            ScheduledAt = new DateTime(2026, 4, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 1,
                            Notes = "Urgent BP follow-up — preeclampsia risk",
                            ScheduledAt = new DateTime(2026, 4, 7, 11, 45, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 2,
                            Notes = "12-week routine check",
                            ScheduledAt = new DateTime(2026, 4, 7, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 4,
                            ScheduledAt = new DateTime(2026, 4, 7, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 5,
                            ScheduledAt = new DateTime(2026, 4, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 3,
                            Notes = "GDM glucose review",
                            ScheduledAt = new DateTime(2026, 4, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.ArticleRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArticleRequests");
                });

            modelBuilder.Entity("MamaCare.API.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("MamaCare.API.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CertificationUrl")
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .HasColumnType("text");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Dr. Mitchell specializes in high-risk pregnancy management with a focus on maternal wellness.",
                            Institution = "Johns Hopkins School of Medicine",
                            LicenseNumber = "MD-49022-OB",
                            Specialty = "Obstetrics & Gynecology",
                            Status = 1,
                            UserId = 6,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Dr. Chen specializes in high-risk pregnancy management and proactive postpartum care.",
                            Institution = "Harvard Medical School",
                            LicenseNumber = "MD-99120-X8",
                            Specialty = "Fetal Medicine Specialist",
                            Status = 0,
                            UserId = 7,
                            YearsOfExperience = 14
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Dr. Rodriguez focuses on neonatal care and newborn health outcomes.",
                            Institution = "Stanford Medical School",
                            LicenseNumber = "MD-31002-NE",
                            Specialty = "Neonatologist",
                            Status = 1,
                            UserId = 8,
                            YearsOfExperience = 9
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.DoctorCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorCertifications");
                });

            modelBuilder.Entity("MamaCare.API.Models.LibraryArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LibraryArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1544126592-807daa2b569b?w=400",
                            PublishedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Optimizing your rest is crucial as you approach delivery.",
                            Title = "Safe Sleep Positions during the Third Trimester",
                            UpdatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400",
                            PublishedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Essential vitamins and nutrients for you and your baby.",
                            Title = "The Third Trimester Diet: What to Eat",
                            UpdatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1518611012118-2969c63b07b7?w=400",
                            PublishedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Safe exercises to keep you active during pregnancy.",
                            Title = "Pregnancy Safety: Gentle Movement Guide",
                            UpdatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=400",
                            PublishedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Summary = "Mindfulness and support strategies for new mothers.",
                            Title = "Managing Postpartum Anxiety",
                            UpdatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400",
                            PublishedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "What to expect and how to prepare in your first 12 weeks.",
                            Title = "First Trimester Essentials",
                            UpdatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1518611012118-2969c63b07b7?w=400",
                            PublishedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Low-impact workouts approved for all trimesters.",
                            Title = "Safe Exercises for Pregnancy",
                            UpdatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("MotherId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SentByDoctor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MotherId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Muraho Dr. Sarah, ndi kumva indwara y'umutwe ikabije kandi amaso yanjye arahumeka.",
                            DoctorId = 1,
                            IsRead = true,
                            MotherId = 1,
                            SentAt = new DateTime(2026, 4, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            SentByDoctor = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "Uwimana, nyamara ukomeze uryamye. Nakiriye ubutumwa bwawe bw'ubuvuzi. Wari wenyine?",
                            DoctorId = 1,
                            IsRead = true,
                            MotherId = 1,
                            SentAt = new DateTime(2026, 4, 7, 13, 3, 0, 0, DateTimeKind.Utc),
                            SentByDoctor = true
                        },
                        new
                        {
                            Id = 3,
                            Content = "Oya, umugabo wanjye ari hano. Indwara y'umutwe irushaho gukabya.",
                            DoctorId = 1,
                            IsRead = false,
                            MotherId = 1,
                            SentAt = new DateTime(2026, 4, 7, 13, 5, 0, 0, DateTimeKind.Utc),
                            SentByDoctor = false
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Mother", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTrimester")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpectedDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GestationalWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("HasGestationalDiabetes")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("text");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mothers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "Penicillin",
                            BloodType = 8,
                            CurrentTrimester = 2,
                            DateOfBirth = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDueDate = new DateTime(2026, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            GestationalWeek = 28,
                            HasGestationalDiabetes = false,
                            HasHypertension = true,
                            Location = "Kigali, Rwanda",
                            OnboardingComplete = true,
                            RiskLevel = 2,
                            UserId = 1,
                            WeightKg = 72.0
                        },
                        new
                        {
                            Id = 2,
                            BloodType = 8,
                            CurrentTrimester = 1,
                            DateOfBirth = new DateTime(1999, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDueDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            GestationalWeek = 24,
                            HasGestationalDiabetes = false,
                            HasHypertension = false,
                            Location = "Musanze, Rwanda",
                            OnboardingComplete = true,
                            RiskLevel = 0,
                            UserId = 2,
                            WeightKg = 70.0
                        },
                        new
                        {
                            Id = 3,
                            BloodType = 8,
                            CurrentTrimester = 2,
                            DateOfBirth = new DateTime(1993, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDueDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            GestationalWeek = 31,
                            HasGestationalDiabetes = true,
                            HasHypertension = true,
                            Location = "Huye, Rwanda",
                            OnboardingComplete = true,
                            RiskLevel = 2,
                            UserId = 3,
                            WeightKg = 78.0
                        },
                        new
                        {
                            Id = 4,
                            BloodType = 8,
                            CurrentTrimester = 0,
                            DateOfBirth = new DateTime(2001, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDueDate = new DateTime(2027, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            GestationalWeek = 12,
                            HasGestationalDiabetes = false,
                            HasHypertension = false,
                            Location = "Rubavu, Rwanda",
                            OnboardingComplete = true,
                            RiskLevel = 1,
                            UserId = 4,
                            WeightKg = 64.0
                        },
                        new
                        {
                            Id = 5,
                            BloodType = 8,
                            CurrentTrimester = 2,
                            DateOfBirth = new DateTime(1990, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedDueDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            GestationalWeek = 38,
                            HasGestationalDiabetes = false,
                            HasHypertension = false,
                            Location = "Nyagatare, Rwanda",
                            OnboardingComplete = true,
                            RiskLevel = 0,
                            UserId = 5,
                            WeightKg = 76.0
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("WeeksPregnant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MamaCare.API.Models.PatientAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAppointments");
                });

            modelBuilder.Entity("MamaCare.API.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MotherId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MotherId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MamaCare.API.Models.TriageSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiRecommendation")
                        .HasColumnType("text");

                    b.Property<double?>("BloodPressureDiastolic")
                        .HasColumnType("double precision");

                    b.Property<double?>("BloodPressureSystolic")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DurationDescription")
                        .HasColumnType("text");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("double precision");

                    b.Property<int>("MotherId")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("TriageSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiRecommendation = "Immediate medical attention required. Symptoms consistent with preeclampsia.",
                            BloodPressureDiastolic = 90.0,
                            BloodPressureSystolic = 140.0,
                            CreatedAt = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            DurationDescription = "Started 2 hours ago, worsening",
                            HeartRate = 92.0,
                            MotherId = 1,
                            Outcome = 3,
                            RiskLevel = 0,
                            SeverityScore = 9,
                            Symptoms = "headache_severe,swelling_sudden,vision_blurred",
                            Temperature = 37.200000000000003
                        },
                        new
                        {
                            Id = 2,
                            AiRecommendation = "Rest and hydration recommended. Monitor for 24 hours.",
                            CreatedAt = new DateTime(2026, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            DurationDescription = "Mild, on and off for 2 days",
                            MotherId = 1,
                            Outcome = 1,
                            RiskLevel = 0,
                            SeverityScore = 4,
                            Symptoms = "nausea,fatigue"
                        },
                        new
                        {
                            Id = 3,
                            AiRecommendation = "Elevated BP with symptoms. Contact your doctor today.",
                            BloodPressureDiastolic = 95.0,
                            BloodPressureSystolic = 145.0,
                            CreatedAt = new DateTime(2026, 4, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            DurationDescription = "Persistent for 3 days",
                            HeartRate = 88.0,
                            MotherId = 3,
                            Outcome = 2,
                            RiskLevel = 0,
                            SeverityScore = 5,
                            Symptoms = "headache_mild,fatigue"
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 341, DateTimeKind.Utc).AddTicks(9911),
                            Email = "uwimana@mamacare.app",
                            FullName = "Uwimana Clarisse",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+250 788 100 001",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2418),
                            Email = "mukamana@mamacare.app",
                            FullName = "Mukamana Espérance",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+250 788 100 002",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2420),
                            Email = "niyonsenga@mamacare.app",
                            FullName = "Niyonsenga Vestine",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+250 788 100 003",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2422),
                            Email = "uwase@mamacare.app",
                            FullName = "Uwase Alphonsine",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+250 788 100 004",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2423),
                            Email = "ingabire@mamacare.app",
                            FullName = "Ingabire Solange",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+250 788 100 005",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2445),
                            Email = "s.mitchell@mamacare.app",
                            FullName = "Dr. Sarah Mitchell",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+1 (555) 092-1111",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2447),
                            Email = "m.chen@mamacare.app",
                            FullName = "Dr. Michael Chen",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+1 (555) 092-4411",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2448),
                            Email = "e.rodriguez@mamacare.app",
                            FullName = "Dr. Elena Rodriguez",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            PhoneNumber = "+1 (555) 092-5522",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=100",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 21, 22, 55, 56, 342, DateTimeKind.Utc).AddTicks(2449),
                            Email = "admin@mamacare.app",
                            FullName = "Admin Sarah",
                            PasswordHash = "$2a$11$/Sh.lP5iSGFbtdSo7wfzhetzKL8bdBd63U56bq6fYl8AIBT9jHIKW",
                            Role = 2
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.VitalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("BloodPressureDiastolic")
                        .HasColumnType("double precision");

                    b.Property<double?>("BloodPressureSystolic")
                        .HasColumnType("double precision");

                    b.Property<double?>("FetalHeartRate")
                        .HasColumnType("double precision");

                    b.Property<int>("MotherId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("VitalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodPressureDiastolic = 90.0,
                            BloodPressureSystolic = 140.0,
                            FetalHeartRate = 142.0,
                            MotherId = 1,
                            Notes = "Elevated BP — monitoring",
                            RecordedAt = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Temperature = 37.100000000000001,
                            WeightKg = 72.0
                        },
                        new
                        {
                            Id = 2,
                            BloodPressureDiastolic = 88.0,
                            BloodPressureSystolic = 138.0,
                            FetalHeartRate = 145.0,
                            MotherId = 1,
                            RecordedAt = new DateTime(2026, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 71.5
                        },
                        new
                        {
                            Id = 3,
                            BloodPressureDiastolic = 72.0,
                            BloodPressureSystolic = 118.0,
                            FetalHeartRate = 148.0,
                            MotherId = 2,
                            RecordedAt = new DateTime(2026, 4, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 70.0
                        },
                        new
                        {
                            Id = 4,
                            BloodPressureDiastolic = 95.0,
                            BloodPressureSystolic = 145.0,
                            FetalHeartRate = 138.0,
                            MotherId = 3,
                            Notes = "High BP + glucose elevated",
                            RecordedAt = new DateTime(2026, 4, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 78.0
                        },
                        new
                        {
                            Id = 5,
                            BloodPressureDiastolic = 80.0,
                            BloodPressureSystolic = 120.0,
                            FetalHeartRate = 140.0,
                            MotherId = 5,
                            RecordedAt = new DateTime(2026, 4, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 76.0
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Appointment", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("Appointments")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.Doctor", b =>
                {
                    b.HasOne("MamaCare.API.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MamaCare.API.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaCare.API.Models.DoctorCertification", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany("Certifications")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MamaCare.API.Models.Message", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany("Messages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("Messages")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.Mother", b =>
                {
                    b.HasOne("MamaCare.API.Models.User", "User")
                        .WithOne("Mother")
                        .HasForeignKey("MamaCare.API.Models.Mother", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaCare.API.Models.PatientAppointment", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MamaCare.API.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MamaCare.API.Models.Prescription", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.TriageSession", b =>
                {
                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("TriageSessions")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.VitalRecord", b =>
                {
                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("VitalRecords")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Certifications");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MamaCare.API.Models.Mother", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Messages");

                    b.Navigation("TriageSessions");

                    b.Navigation("VitalRecords");
                });

            modelBuilder.Entity("MamaCare.API.Models.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });
#pragma warning restore 612, 618
        }
    }
}
