// <auto-generated />
using System;
using MamaCare.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamaCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407200925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MamaCare.API.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MotherId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 1,
                            Notes = "28-week anatomy scan",
                            ScheduledAt = new DateTime(2026, 4, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 1,
                            Notes = "Urgent BP follow-up — preeclampsia risk",
                            ScheduledAt = new DateTime(2026, 4, 7, 11, 45, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 2,
                            Notes = "12-week routine check",
                            ScheduledAt = new DateTime(2026, 4, 7, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 4,
                            ScheduledAt = new DateTime(2026, 4, 7, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 5,
                            ScheduledAt = new DateTime(2026, 4, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            MotherId = 3,
                            Notes = "GDM glucose review",
                            ScheduledAt = new DateTime(2026, 4, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Dr. Mitchell specializes in high-risk pregnancy management with a focus on maternal wellness.",
                            Institution = "Johns Hopkins School of Medicine",
                            LicenseNumber = "MD-49022-OB",
                            Specialty = "Obstetrics & Gynecology",
                            Status = 1,
                            UserId = 6,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Dr. Chen specializes in high-risk pregnancy management and proactive postpartum care.",
                            Institution = "Harvard Medical School",
                            LicenseNumber = "MD-99120-X8",
                            Specialty = "Fetal Medicine Specialist",
                            Status = 0,
                            UserId = 7,
                            YearsOfExperience = 14
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Dr. Rodriguez focuses on neonatal care and newborn health outcomes.",
                            Institution = "Stanford Medical School",
                            LicenseNumber = "MD-31002-NE",
                            Specialty = "Neonatologist",
                            Status = 1,
                            UserId = 8,
                            YearsOfExperience = 9
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.LibraryArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LibraryArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1544126592-807daa2b569b?w=400",
                            PublishedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Optimizing your rest is crucial as you approach delivery.",
                            Title = "Safe Sleep Positions during the Third Trimester",
                            UpdatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400",
                            PublishedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Essential vitamins and nutrients for you and your baby.",
                            Title = "The Third Trimester Diet: What to Eat",
                            UpdatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1518611012118-2969c63b07b7?w=400",
                            PublishedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Safe exercises to keep you active during pregnancy.",
                            Title = "Pregnancy Safety: Gentle Movement Guide",
                            UpdatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=400",
                            PublishedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Summary = "Mindfulness and support strategies for new mothers.",
                            Title = "Managing Postpartum Anxiety",
                            UpdatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400",
                            PublishedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "What to expect and how to prepare in your first 12 weeks.",
                            Title = "First Trimester Essentials",
                            UpdatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1518611012118-2969c63b07b7?w=400",
                            PublishedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Summary = "Low-impact workouts approved for all trimesters.",
                            Title = "Safe Exercises for Pregnancy",
                            UpdatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SentByDoctor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MotherId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello Dr. Sarah, I'm feeling very dizzy and my vision is spotting.",
                            DoctorId = 1,
                            IsRead = true,
                            MotherId = 1,
                            SentAt = new DateTime(2026, 4, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            SentByDoctor = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "Aline, please remain seated. I have received your triage alert. Are you alone?",
                            DoctorId = 1,
                            IsRead = true,
                            MotherId = 1,
                            SentAt = new DateTime(2026, 4, 7, 13, 3, 0, 0, DateTimeKind.Utc),
                            SentByDoctor = true
                        },
                        new
                        {
                            Id = 3,
                            Content = "No, my husband is with me. The headache is getting worse.",
                            DoctorId = 1,
                            IsRead = false,
                            MotherId = 1,
                            SentAt = new DateTime(2026, 4, 7, 13, 5, 0, 0, DateTimeKind.Utc),
                            SentByDoctor = false
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Mother", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentTrimester")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GestationalWeek")
                        .HasColumnType("int");

                    b.Property<bool>("HasGestationalDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("bit");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mothers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "Penicillin",
                            CurrentTrimester = 2,
                            DateOfBirth = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedDueDate = new DateTime(2026, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GestationalWeek = 28,
                            HasGestationalDiabetes = false,
                            HasHypertension = true,
                            Location = "Seattle, WA",
                            OnboardingComplete = true,
                            RiskLevel = 2,
                            UserId = 1,
                            WeightKg = 72.0
                        },
                        new
                        {
                            Id = 2,
                            CurrentTrimester = 1,
                            DateOfBirth = new DateTime(1999, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedDueDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GestationalWeek = 24,
                            HasGestationalDiabetes = false,
                            HasHypertension = false,
                            Location = "Portland, OR",
                            OnboardingComplete = true,
                            RiskLevel = 0,
                            UserId = 2,
                            WeightKg = 70.0
                        },
                        new
                        {
                            Id = 3,
                            CurrentTrimester = 2,
                            DateOfBirth = new DateTime(1993, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedDueDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GestationalWeek = 31,
                            HasGestationalDiabetes = true,
                            HasHypertension = true,
                            Location = "Austin, TX",
                            OnboardingComplete = true,
                            RiskLevel = 2,
                            UserId = 3,
                            WeightKg = 78.0
                        },
                        new
                        {
                            Id = 4,
                            CurrentTrimester = 0,
                            DateOfBirth = new DateTime(2001, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedDueDate = new DateTime(2027, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GestationalWeek = 12,
                            HasGestationalDiabetes = false,
                            HasHypertension = false,
                            Location = "Denver, CO",
                            OnboardingComplete = true,
                            RiskLevel = 1,
                            UserId = 4,
                            WeightKg = 64.0
                        },
                        new
                        {
                            Id = 5,
                            CurrentTrimester = 2,
                            DateOfBirth = new DateTime(1990, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedDueDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GestationalWeek = 38,
                            HasGestationalDiabetes = false,
                            HasHypertension = false,
                            Location = "Chicago, IL",
                            OnboardingComplete = true,
                            RiskLevel = 0,
                            UserId = 5,
                            WeightKg = 76.0
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.TriageSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiRecommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BloodPressureDiastolic")
                        .HasColumnType("float");

                    b.Property<double?>("BloodPressureSystolic")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DurationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("float");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("TriageSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiRecommendation = "Immediate medical attention required. Symptoms consistent with preeclampsia.",
                            BloodPressureDiastolic = 90.0,
                            BloodPressureSystolic = 140.0,
                            CreatedAt = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            DurationDescription = "Started 2 hours ago, worsening",
                            HeartRate = 92.0,
                            MotherId = 1,
                            Outcome = 3,
                            SeverityScore = 9,
                            Symptoms = "headache_severe,swelling_sudden,vision_blurred",
                            Temperature = 37.200000000000003
                        },
                        new
                        {
                            Id = 2,
                            AiRecommendation = "Rest and hydration recommended. Monitor for 24 hours.",
                            CreatedAt = new DateTime(2026, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            DurationDescription = "Mild, on and off for 2 days",
                            MotherId = 1,
                            Outcome = 1,
                            SeverityScore = 4,
                            Symptoms = "nausea,fatigue"
                        },
                        new
                        {
                            Id = 3,
                            AiRecommendation = "Elevated BP with symptoms. Contact your doctor today.",
                            BloodPressureDiastolic = 95.0,
                            BloodPressureSystolic = 145.0,
                            CreatedAt = new DateTime(2026, 4, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            DurationDescription = "Persistent for 3 days",
                            HeartRate = 88.0,
                            MotherId = 3,
                            Outcome = 2,
                            SeverityScore = 5,
                            Symptoms = "headache_mild,fatigue"
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(2157),
                            Email = "aline@mamacare.app",
                            FullName = "Aline Silva",
                            PasswordHash = "hashed_pw_1",
                            PhoneNumber = "+1 (555) 012-3456",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6463),
                            Email = "elena@mamacare.app",
                            FullName = "Elena Wright",
                            PasswordHash = "hashed_pw_2",
                            PhoneNumber = "+1 (555) 111-2222",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6469),
                            Email = "maya@mamacare.app",
                            FullName = "Maya Lopez",
                            PasswordHash = "hashed_pw_3",
                            PhoneNumber = "+1 (555) 333-4444",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6471),
                            Email = "sarah.p@mamacare.app",
                            FullName = "Sarah Parker",
                            PasswordHash = "hashed_pw_4",
                            PhoneNumber = "+1 (555) 555-6666",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6472),
                            Email = "ananya@mamacare.app",
                            FullName = "Ananya Kapoor",
                            PasswordHash = "hashed_pw_5",
                            PhoneNumber = "+1 (555) 777-8888",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6474),
                            Email = "s.mitchell@mamacare.app",
                            FullName = "Dr. Sarah Mitchell",
                            PasswordHash = "hashed_pw_6",
                            PhoneNumber = "+1 (555) 092-1111",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6475),
                            Email = "m.chen@mamacare.app",
                            FullName = "Dr. Michael Chen",
                            PasswordHash = "hashed_pw_7",
                            PhoneNumber = "+1 (555) 092-4411",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6477),
                            Email = "e.rodriguez@mamacare.app",
                            FullName = "Dr. Elena Rodriguez",
                            PasswordHash = "hashed_pw_8",
                            PhoneNumber = "+1 (555) 092-5522",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=100",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 7, 20, 9, 24, 773, DateTimeKind.Utc).AddTicks(6478),
                            Email = "admin@mamacare.app",
                            FullName = "Admin Sarah",
                            PasswordHash = "hashed_pw_9",
                            Role = 2
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.VitalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BloodPressureDiastolic")
                        .HasColumnType("float");

                    b.Property<double?>("BloodPressureSystolic")
                        .HasColumnType("float");

                    b.Property<double?>("FetalHeartRate")
                        .HasColumnType("float");

                    b.Property<int>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MotherId");

                    b.ToTable("VitalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodPressureDiastolic = 90.0,
                            BloodPressureSystolic = 140.0,
                            FetalHeartRate = 142.0,
                            MotherId = 1,
                            Notes = "Elevated BP — monitoring",
                            RecordedAt = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Temperature = 37.100000000000001,
                            WeightKg = 72.0
                        },
                        new
                        {
                            Id = 2,
                            BloodPressureDiastolic = 88.0,
                            BloodPressureSystolic = 138.0,
                            FetalHeartRate = 145.0,
                            MotherId = 1,
                            RecordedAt = new DateTime(2026, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 71.5
                        },
                        new
                        {
                            Id = 3,
                            BloodPressureDiastolic = 72.0,
                            BloodPressureSystolic = 118.0,
                            FetalHeartRate = 148.0,
                            MotherId = 2,
                            RecordedAt = new DateTime(2026, 4, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 70.0
                        },
                        new
                        {
                            Id = 4,
                            BloodPressureDiastolic = 95.0,
                            BloodPressureSystolic = 145.0,
                            FetalHeartRate = 138.0,
                            MotherId = 3,
                            Notes = "High BP + glucose elevated",
                            RecordedAt = new DateTime(2026, 4, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 78.0
                        },
                        new
                        {
                            Id = 5,
                            BloodPressureDiastolic = 80.0,
                            BloodPressureSystolic = 120.0,
                            FetalHeartRate = 140.0,
                            MotherId = 5,
                            RecordedAt = new DateTime(2026, 4, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            WeightKg = 76.0
                        });
                });

            modelBuilder.Entity("MamaCare.API.Models.Appointment", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("Appointments")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.Doctor", b =>
                {
                    b.HasOne("MamaCare.API.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MamaCare.API.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaCare.API.Models.Message", b =>
                {
                    b.HasOne("MamaCare.API.Models.Doctor", "Doctor")
                        .WithMany("Messages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("Messages")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.Mother", b =>
                {
                    b.HasOne("MamaCare.API.Models.User", "User")
                        .WithOne("Mother")
                        .HasForeignKey("MamaCare.API.Models.Mother", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaCare.API.Models.TriageSession", b =>
                {
                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("TriageSessions")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.VitalRecord", b =>
                {
                    b.HasOne("MamaCare.API.Models.Mother", "Mother")
                        .WithMany("VitalRecords")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("MamaCare.API.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MamaCare.API.Models.Mother", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Messages");

                    b.Navigation("TriageSessions");

                    b.Navigation("VitalRecords");
                });

            modelBuilder.Entity("MamaCare.API.Models.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Mother");
                });
#pragma warning restore 612, 618
        }
    }
}
